# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Desktop with Gradle
      run: ./gradlew desktop:dist
    - name: Build HTML with Gradle
      run: ./gradlew html:dist
    - name: Push desktop/build/libs to master and html/build/dist to gh-pages branch
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add desktop/build/libs
        git commit -m "Automated build for Desktop"
        git push origin master
        git add html/build/dist
        git commit -m "Automated build for HTML"
        git subtree push --prefix html/build/dist origin gh-pages -f
